# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# We need to be able to reclone the repo so it can't be shallow
git:
  depth: false


php:
  - 7.0
  - 7.1
  - 7.2
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script: bash -x .travis.bash

script: phpUnitQuickTests=0 ./bin/qa