sudo: required
dist: trusty
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --window-size=1920,1080 --start-maximised http://localhost &
language: php
git:
  depth: false
php:
- 7.0
- 7.1
- 7.2
- hhvm
matrix:
  allow_failures:
  - php: hhvm
before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
  - "bash -x .travis.bash"
script: phpUnitQuickTests=0 ./bin/qa
notifications:
  slack:
    on_success: change
    rooms:
      - secure: HDzq1c/+sAum3mp2/IdVLKtShkCTMJXindoRmrRZYNIMfM65br8FxdeblY51IS6PZXCl/nYpBfBNtsNQhrSqPCEVntnbaWJXezNfFAXNO8QHGFYQ3e0lcAFeEwc+gAH61BNYAGu0HH1+8QiF48VG/rMl72mnpxXvdfgkk6UIsKXzQid2EAiVPO8scLpy1qIl5LMljcA0QpEAx3vtr7B1LtBZ5WfLQ99lUpdQ2QEphFjTyF+HKXa8F+0PBIM8tgZo9ThnPuL4ijq8YecFYzkOX5v71hehNRjzizeVDlgfZ3WNNT82XLOxRQK3T1zKTKLfdsL8HgPFAZHog+ggJpicdmIjFGPni68NwN2v2axuEOUybWO6/83iaV0sSrhdtvGgiads1LveuZIYEYp85UvstdJkW9USPbhATXu8uc/2WrUOXSmLUOmZtrNZY092RukAnUjrApwvYw5Wf8m4O8eL8Tjkhxoh5gmIZeCj5rbz8UFmIjthFHoDoTLY8Q3SOMjaW5GAiPNd60hkkUC1BKjJEcNP43xJsMT/jKMcMoTEoh+b4S/rAXuuKt/6SXwX7IA3YNZgbm8LfRg+SkwxyEtjLM3+yNViQkd+oKxDqa99nu95b9TiblEPYEZ1WZTHBiUkY3yEPrmU+IwvmWxDJuqkCEtkzJDfFZrxfpmTOAX+XBY=
